-- 코드를 작성해주세요
SELECT ROUTE, CONCAT(ROUND(SUM(D_BETWEEN_DIST),1),'km') AS 'TOTAL_DISTANCE', CONCAT(ROUND(AVG(D_BETWEEN_DIST),2),'km') AS 'AVERAGE_DISTANCE'
FROM SUBWAY_DISTANCE
GROUP BY ROUTE
ORDER BY SUM(D_BETWEEN_DIST) DESC;
# ORDER BY는 그대로.. 여기선 CONCAT 때문에 문자열로 인식됐을수도 있고, 반올림 한다음에 정렬하는거라 정확하지 않을수 있음.